### PR TITLE
Fixed Core-491 Add a MotionEvent

### PR DESCRIPTION
**Pull request by mcicolella**

### CODE REVIEW

**Comment by mcicolella** [comment]
My idea is to trace movements when there is an acceleration or 3axes change. Of course the hardware device should send an event only if there is any value change.
Eg. If inclination goes from 30 to 35 degrees -> send an event
      if inclination is constant (no change) -> don't send any event (it needen't to notify the current value continously)

**Comment by gpulido** [comment]
Hello,

Just as a complementary comment, this is a perfect use of a Kalman filter,
have you take a look on them?

Gabriel

2015-02-04 18:29 GMT+01:00 Mauro Cicolella <notifications@github.com>:

**Comment by enriconicoletti** [comment]
we should differentate between gyroscope and accelerometer http://www.livescience.com/40103-accelerometer-vs-gyroscope.html

from what you said you proabably want to find the orientation of the device (gyroscope) not detecting if it's moving (accelerometer). 

Anyway we cannot have an event which fires anytime an acceleration is detected. What you can do is notify an "activity" bases on accelerometer patterns: for example bouncing, turning, falling, ... and this should be computed on the axis acceleration (here is where @gpulido suggestion can/should be used)

The semantic of this event is not clearly defined. On one side it allows to report motions level in a image (I suppose because it is an int). Then there is distance which implies an "observed motion" of some kind. Then there are the accelerometer and gyroscope values that implies "self motion". Another parameter is location which is a single point in space which is very ambiguous if related to motion, it should be documented carefully, at least.

Please define a clear scope for this event (CameraDetectsMotion, DeviceOrientation, DeviceIsMoving, LocationEvent, ...) and change it accordingly documenting it's use cases.

**Comment by mcicolella** [comment]
Maybe it's better to have different detection events for different devices: CameraMotionDetected, PIRMotionDetected etc.

**Comment by enriconicoletti** [comment]
Ok, I'm closing this pull request until we identify a list of motion events to implement

**Pull request closed without merging**
