### PR TITLE
update Pushsafer.com

### PR DESCRIPTION
**Pull request by appzer**
to send also urls or url schemes

### CODE REVIEW

**Comment by appzer** [comment]
When is the pushsafer integration available in the marketplace for download. Or is there an other way to integrate it.

**Comment by mcicolella** [comment]
@appzer The plugin will be available after merging this PR. The documentation is available on http://freedomotic.com/content/plugins/push-notifications . We must update with your service.

**Comment by appzer** [comment]
@mcicolella can you give me feedback, when the plugin is downloadable and when you have revised the plugin page http://freedomotic.com/content/plugins/push-notifications

After that i will integrate freedomotic to pushsafer.com

Thanks Kevin

**Comment by mcicolella** [comment]
Integrated! Thanks

**Pull request closed without merging**
