### PR TITLE
issue 166 solved over updated master

### PR DESCRIPTION
**Pull request by P3trur0**
This solves issue #166.

### CODE REVIEW

**Comment by mcicolella** [comment]
@P3trur0  "ALL" level seems not working. Can you check please?

**Comment by P3trur0** [comment]
@mcicolella sure, I'll take a look tonight.

**Comment by P3trur0** [comment]
HI @mcicolella, now the **ALL** log level should be ok.
Please, take a look!

**Comment by mcicolella** [comment]
Integrated! Good work, thanks.

**Pull request closed without merging**
