### PR TITLE
Missing Jackson Databind dependency added. Jackson Annotations dependency bumped

### PR DESCRIPTION
**Pull request by P3trur0**
Hi there!

I see that this error happens because of the Jackson Databind dependency missing.

Also, I take the opportunity to bump the Jackson Annotations dependency to the **2.8.9** version.

Please see if this solves the issue.

Have a nice evening,

@P3trur0

### CODE REVIEW

**Comment by mcicolella** [comment]
@P3trur0 sorry but it creates a conflict with the RestAPI plugin. Have you tried it before sending the PR?
Here the log (only a brief summary)
`2017-06-30 08:36:41,237 ERROR [main] - Failed to initialize Atmosphere Framework
java.lang.NoSuchMethodError: jersey.repackaged.com.google.common.collect.Iterables.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Ljava/lang/Iterable;
	at org.glassfish.jersey.server.internal.ConfigHelper.getContainerLifecycleListener(ConfigHelper.java:92)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:171)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:358)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.atmosphere.util.AtmosphereFilterChain.init(AtmosphereFilterChain.java:89)
	at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWrapper.init(ReflectorServletProcessor.java:297)
	at org.atmosphere.handler.ReflectorServletProcessor.init(ReflectorServletProcessor.java:176)
	at org.atmosphere.annotation.AtmosphereServiceProcessor$1.init(AtmosphereServiceProcessor.java:107)
	at org.atmosphere.cpr.AtmosphereFramework.initAtmosphereHandler(AtmosphereFramework.java:1573)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:891)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:780)
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:101)
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:80)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
`

**Comment by P3trur0** [comment]
@mcicolella Yep, I tried my changes and I was seeing that exception too, but it was occurring also in my master branch, so I did assume it was caused by something else.
It seems related, again, to a dependency problem (i.e.: **java.lang.NoSuchMethodError**).

However, can I update also the Jersey dependency in case?

**Comment by mcicolella** [comment]
@P3trur0 maybe the problem is related to the upgrade of jackson-annotations dependency from 2.6.2 to 2.8.9 but I'm not sure.
@bestmazzo can you help us? Is the same conflict you faced in the past?

**Comment by P3trur0** [comment]
@mcicolella see [here](https://stackoverflow.com/questions/35082976/restful-web-service-java-lang-nosuchmethoderror-concatljava-lang-iterablelja#35083574).

Could this be the moment to update also this dependency, then?

**Comment by mcicolella** [comment]
@P3trur0 do you mean to update guava to 22.0 version?

**Comment by P3trur0** [comment]
@mcicolella actually the problem was because of a missing library in `restapi-v3` plugin.
This PR now should be fine.

Then, at the moment we are not able to update Guava's version because of a transitive dependency in `persistence` plugin (i.e.: datastax Cassandra driver).

**Comment by mcicolella** [comment]
@P3trur0 I still have the following exception but only on Linux 64 bit. On Windows it works fine.

`2017-07-03 08:47:00,925 WARN  [main] - FAILED org.glassfish.jersey.servlet.ServletContainer-213860b8: java.lang.NoSuchMethodError: jersey.repackaged.com.google.common.collect.Iterables.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Ljava/lang/Iterable;
java.lang.NoSuchMethodError: jersey.repackaged.com.google.common.collect.Iterables.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Ljava/lang/Iterable;
	at org.glassfish.jersey.server.internal.ConfigHelper.getContainerLifecycleListener(ConfigHelper.java:92)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:171)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:358)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at com.freedomotic.plugins.devices.restapiv3.RestJettyServer.startServer(RestJettyServer.java:158)
	at com.freedomotic.plugins.devices.restapiv3.RestAPIv3.onStart(RestAPIv3.java:88)
	at com.freedomotic.api.Protocol$1.run(Protocol.java:138)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at com.freedomotic.api.Protocol.start(Protocol.java:160)
	at com.freedomotic.app.Freedomotic.start(Freedomotic.java:307)
	at com.freedomotic.app.Freedomotic.main(Freedomotic.java:439)
`

Have you tried it?

**Comment by P3trur0** [comment]
@mcicolella, sure I did.
Instead, did you perform a proper clean and maven build also on Linux machine?

As you might notice, the error is of method not found: this happens because of a missing dependency.

For the sake of completeness, I am working on a Linux 32 bit machine.

**Comment by mcicolella** [comment]
@P3trur0 Yes. I made another test. On Windows it works so I copied the entire Freedomotic package on Linux machine and there the problem appears. It's strange. But have you tried also on Linux 64 bit?

**Comment by P3trur0** [comment]
@mcicolella no: I have not a Linux 64 bit machine available so far. However, AFAIK, all the dependencies are fine now. Please, try to run a proper build on a Linux environment though.

**Comment by mcicolella** [comment]
@P3trur0 the build on Linux is OK and the application works fine. The problem appears when you install Telegram plugin. At startup the previous and many other exceptions are raised. At this point Telegram plugin works but not RestAPI. 
Have you tried with Telegram plugin?

**Comment by P3trur0** [comment]
@mcicolella, yes I did.

Tonight I'll take a look again at the execution log again to see if any other error appears.

However, in my opinion, the operating system is not the cause of the problem.

Do the machines you're using have the same JVM version?

**Comment by amenak77** [comment]
I confirm successfull test with win 10 home 64 bit, bot telegram plugin and RESTapi plugin

**Comment by mcicolella** [comment]
I'm closing this PR. Issue fixed in 83c54784156e0f77087904cd568047caa6bcb458

**Pull request closed without merging**
