### PR TITLE
removed slf4j JUL bridge

### PR DESCRIPTION
**Pull request by P3trur0**
This PR removes the `java.util.logging` bridge of slf4j that blocked the `LogViewer` class to print log messages on the GUI.

It solves #166

### CODE REVIEW

**Comment by mcicolella** [comment]
@P3trur0 can you update this PR with the last changes to the framework? Thanks

**Comment by P3trur0** [comment]
@mcicolella Yes I'll do ASAP.

**Comment by P3trur0** [comment]
Hi @mcicolella please, see if I am doing right here.

**Comment by mcicolella** [comment]
@P3trur0 sorry there are still some conflicting files. Maybe it should be better to create a new PR with only the original changes (in the first 2 commits).

**Comment by P3trur0** [comment]
@mcicolella ok then, so tonight I'll perform a cleaner PR directly from the master branch.

**Comment by P3trur0** [comment]
Closing this PR since I am going to open another one over a fresh branch.

**Pull request closed without merging**
