### PR TITLE
Improve logging in mqttclient plugin

### PR DESCRIPTION
**Pull request by atanasg**
Replaced all System.out.println(...) calls with LOG.info(...) calls. Also
made the logger of MqttClient4FD private in order to make sure that
messages in the log come from the correct class. Otherwise debugging will
be harder as problems in Mqtt will be logged from MqttCleint4FD and
developers would start to search in that class.

This pull request contributes to issue #209.

### CODE REVIEW

**Comment by mcicolella** [comment]
LOG.severe should be changed by LOG.error

**Comment by atanasg** [comment]
There is no level "error" in https://docs.oracle.com/javase/8/docs/api/java/util/logging/Level.html. One of the following can be used:

* SEVERE (highest value)
* WARNING
* INFO

**Comment by mcicolella** [comment]
Sorry I forgot to write in the issue we are switching to SLF4J.

**Comment by atanasg** [comment]
Ok, I will adapt the pull request accordingly

**Comment by mcicolella** [comment]
Integrated! Thanks

**Pull request closed without merging**
