### PR TITLE
Fix sonarcloud issues in Restapiv3/utils

### PR DESCRIPTION
**Pull request by pushkyn**
Resolving #346

### CODE REVIEW

**Comment by mcicolella** [comment]
COMPILATION ERROR : 
-------------------------------------------------------------
com/freedomotic/plugins/devices/restapiv3/resources/jersey/UserCommandResource.java:[117,21] create(com.freedomotic.reactions.Command) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.UserCommandResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/EnvironmentResource.java:[121,21] create(com.freedomotic.model.environment.Environment) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.EnvironmentResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/RoomResource.java:[134,21] create(com.freedomotic.model.environment.Zone) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.RoomResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/ThingResource.java:[145,21] create(com.freedomotic.model.object.EnvObject) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.ThingResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/ReactionResource.java:[117,21] create(com.freedomotic.plugins.devices.restapiv3.representations.ReactionRepresentation) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.ReactionResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/UserResource.java:[83,21] create(com.freedomotic.plugins.devices.restapiv3.representations.UserRepresentation) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.UserResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/TriggerResource.java:[115,21] create(com.freedomotic.reactions.Trigger) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.TriggerResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
com/freedomotic/plugins/devices/restapiv3/resources/jersey/HardwareCommandResource.java:[94,21] create(com.freedomotic.reactions.Command) in com.freedomotic.plugins.devices.restapiv3.resources.jersey.HardwareCommandResource cannot override create(T) in com.freedomotic.plugins.devices.restapiv3.utils.AbstractResource
  overridden method does not throw java.net.URISyntaxException
8 errors

**Comment by mcicolella** [comment]
Have you compiled and run the program before sending the PR?

**Comment by pushkyn** [comment]
I forgot to make a final check, I'm sorry. Now all exceptions are fixed.

**Comment by mcicolella** [comment]
Why did you remove `throws URISyntaxException` ?

**Comment by pushkyn** [comment]
@mcicolella - `AbstractResource.create` method don't throw this exception because we have the `catch` statement inside.

**Pull request merged**
