### PR TITLE
Adds password hashing and removes plain text passwords.

### LINKED ISSUE #132: Authc: secure passwords into privileges file
Users' password is now kept in plaintext into privileges.conf file.
We should store them in an encrypted way.

### PR DESCRIPTION
**Pull request by dmitraver**
Fixes #132 

Adds password hashing and replaces plain text passwords with their sha-256 hashed and salted counterparts.

### CODE REVIEW

**Comment by dmitraver** [comment]
Hi @bestmazzo

Please take a look once you have time ;)

**Comment by dmitraver** [comment]
Hi @bestmazzo, @mcicolella

Please take a look once you have time ;)

**Comment by mcicolella** [comment]
@dmitraver Thanks, I'll review asap

**Comment by bestmazzo** [comment]
Integrated
@dmitraver , thank you very much for your contribution!

**Pull request closed without merging**
